export * from "./home"
export * from "./register"
export * from "./login"
export * from "./about"
export * from "./notFound"
export * from "./cart"
export * from "./products"
export * from "./wishlist"